Integration tests are important for your systems as they catch system-level issues that unit tests miss, whilst being faster than end-to-end tests.

When writing these tests we want to make sure that these tests are reliable, able to be reproduced and can isolate our system failures. This is why we want to use a testing framework like `jest`, and use a http testing library like `supertest`.

```
yarn add --dev jest supertest @types/jest @types/supertest
```

## Writing the API

We will write a small API to do some testing on.

First define the resources:

```ts
// resources/apis.ts
import { api } from '@nitric/sdk';

export const helloApi = api('main');
```

```ts
// resources/buckets.ts
import { bucket } from '@nitric/sdk';

export const imageBucket = bucket('images');
```

The trick for unit testing is that we want to define our functions separately from the routes, as testing anonymous functions in the route callback is difficult. Thus, we'll split them like this:

```ts
// functions/hello.ts
import { imageBucket } from '../resources/buckets';
import { helloApi } from '../resources/apis';

export const imageWriter = imageBucket.for('writing');

export const handleHello = async (ctx: any) => {
  const { name } = ctx.req.params;

  ctx.res.body = `Hello ${name}`;

  return ctx;
};

export const handleAddImage = async (ctx: any) => {
  const { name } = ctx.req.params;

  await imageWriter.file(name).write(Buffer.from(name));

  ctx.res.body = `Successfully added '${name}' image to bucket!`;

  return ctx;
};

helloApi.get('/:name', handleHello);
helloApi.post('/:name', handleAddImage);
```

## Writing the Tests

### Asserting

Put the unit tests in a test directory, and name it `unit.test.ts`. The logic being split out into separate functions makes it very easy to test our API.

We are first testing that if the function is passed a context with a set name parameter, it should return the same context, but with a body added to the response. The function handleHello is asynchronous, therefore we await it, expecting it to resolve to the expected value.

```ts
import { handleHello } from '../functions/hello';

describe('Testing Hello Function', () => {
  const ctx = { req: { params: { name: 'Test' } }, res: { body: '' } };

  describe('Given we want a greeting', () => {
    test('responds with Hello Test', async () => {
      await expect(handleHello(ctx)).resolves.toEqual({
        ...ctx,
        res: {
          body: 'Hello Test',
        },
      });
    });
  });
});
```

### Mocking

Our next function handleAddImage becomes more complex because it uses a bucket. This will need to be mocked as we want our unit tests to be fast, replicable, and isolated. By mocking a production system, we have an isolated environment that won't be effected by changes in the system. The trade-off is that the unit tests won't catch system-level failures. However, this is covered by [integration tests](/docs/reference/tests/integration-testing).

We'll go over it section by section, but here is the full example of these tests:

```ts
  ...

  describe('Given we want to add a new image to a bucket', () => {

    let writerSpy;
    let bucketSpy;
    let handleAddImage;
    beforeAll(async () => {
      writerSpy = jest.spyOn(File.prototype, 'write');
      bucketSpy = jest.spyOn(BucketResource.prototype, 'for');

      // Doing dynamic imports to mock the BucketResource.for
      const helloModule = await import('../functions/hello');
      handleAddImage = helloModule.handleAddImage;
    })

    afterAll(() => {
      jest.resetAllMocks();
    });

    beforeEach(() => {
      jest.clearAllMocks();
    })

    test('adds a new image to the bucket', async () => {
      writerSpy.mockResolvedValue();

      await expect(handleAddImage(ctx))
        .resolves.toEqual({
          ...ctx,
          res: {
            body: "Successfully added 'Test' to user collection"
          }
        })

      expect(writerSpy).toBeCalledTimes(1)
    });

    test('throws an error', async () => {
      writerSpy.mockRejectedValue(new Error('Mock error'))

      await expect(handleAddImage(ctx)).rejects.toEqual(Error('Mock error'))

      expect(writerSpy).toBeCalledTimes(1)
    });
  });
```

Lets start by looking at the mocks. These are done in the beforeAll function, which means it happens before all the tests are run.

The functions to create a bucket 'for' and the call to write to a bucket 'write' will make gRPC calls on the backend. This means that they need to be mocked, as there is nothing for it to call to, and thus will result in an UNAVAILABLE error. We mock these using jest's spyOn functions on the object prototype.

This works fine for mocking the `write` method as its within the `handleAddImage` function, but the `for` method is called when the module is imported. Therefore, we add a dynamic import after the `for` method is mocked.

```ts
import { File, BucketResouce } from '@nitric/sdk';

...

let writerSpy;
let bucketSpy;
let handleAddImage;
beforeAll(async () => {
  writerSpy = jest.spyOn(File.prototype, 'write');
  bucketSpy = jest.spyOn(BucketResource.prototype, 'for');

  // Doing dynamic imports to include the BucketResource.for method mock
  const helloModule = await import('../functions/hello');
  handleAddImage = helloModule.handleAddImage;
})
```

We also add `afterAll` and `beforeEach` functions to reset the mocks.

```ts
afterAll(() => {
  jest.resetAllMocks();
});

beforeEach(() => {
  jest.clearAllMocks();
});
```

Now that we have the mocks, we can use them for the tests. The first test is testing that the function will succeed. On a success, the promise will both resolve and have a success message in the body of the context's response.

Update the mock so that it resolves, and check that the `write` function was only called once. The mock can change in the test, as it will be reset before the next test is run.

```ts
test('adds a new image to the bucket', async () => {
  writerSpy.mockResolvedValue();

  await expect(handleAddImage(ctx)).resolves.toEqual({
    ...ctx,
    res: {
      body: "Successfully added 'Test' to user collection",
    },
  });

  expect(writerSpy).toBeCalledTimes(1);
});
```

The next test will instead test a write failure. The failure may be caused by any number of reasons, and therefore we should make sure our function is fit to handle them when they occur.

Change the mock this time so that it rejects with a new error. Still check that the write was called once.

```ts
test('throws an error', async () => {
  writerSpy.mockRejectedValue(new Error('Mock error'));

  await expect(handleAddImage(ctx)).rejects.toEqual(Error('Mock error'));

  expect(writerSpy).toBeCalledTimes(1);
});
```

## Running the tests

The tests can now be run. Add to your `package.json` a test script.

```json
"scripts": {
  "test": "jest"
}
```

You can then run the tests locally with:

```bash
yarn test
```

The output should be something like:

```
  Testing Hello Function
    Given we want a greeting
      ✓ responds with Hello Test (4 ms)
    Given we want to add a new image to a bucket
      ✓ adds a new image to the bucket (5 ms)
      ✓ throws an error (3 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        4.292 s, estimated 7 s
Ran all test suites.
✨  Done in 6.18s.
```
